### ISSUE TITLE
Game freezes when switching to pump shotgun

### ISSUE THREAD

**Issue by Sage009** [pa1nki113r/Project_Brutality#129]
Depending what map I'm playing on, switching to the pump shotty will on rare occasions cause the game to freeze.

**Comment by SaIigia** [comment]
I can confirm that.
But it seems for me that it has something to do with dragon breath/mag upgrade.

**Comment by secretagentjr** [comment]
an infinite loop of a_jumpifinventory was occuring after picking up more than one shotgun magazine upgrade, thus freezing/crashing gzdoom, i figured out what was causing it and it's already fixed in my build

**Comment by JMartinez9820** [comment]
This issue is now resolved, so as a result, this issue here can be closed

**Comment by davidneely** [comment]
I just tried it and can confirm this issue is not resolved. Running latest version of PB test build and stable GZDoom. Game freezes completely when scrolling through shotguns. I can get it to do this every time by entering "give all" twice in the console, then "summon upgradespawner" and picking them up until it starts only spawning backpacks.

**Comment by JMartinez9820** [comment]
@davidneely Please update by downloading the Github build again. It got updated 6 days ago and has fixed the Shotgun Magazine issue

**Comment by JMartinez9820** [comment]
If that doesn't work use this:
https://drive.google.com/file/d/1kRuqbMLe5dO_8z6yRHCwqI2__56lckhW/view?usp=drivesdk

**Comment by davidneely** [comment]
@JMartinez9820 Sorry if I wasn't clear in my original message, I am using the latest Github build, downloaded as of a couple hours ago.

The issue is still occurring, even after using the PBShotgunMagCrashHotfix3 pk3.

It specifically does not do it on the first switch, but after the second or third, when moving from pump shotgun to double / quad barrel. That's when the game locks up.

**Comment by davidneely** [comment]
Just tried the most recent version (Github unstable release as of 2019-07-19) and this issue appears to be completely resolved. I did need to update my version of GZDoom from 3.7.1 (I believe) to 4.1.3 -- it is possible this is what was causing the problem before.

**Comment by scaryred24** [comment]
That would be very possible. I do remember 3.7.x giving me issues in the past. When a hotfix is released, always upgrade to that as the first release of a minor or major release is never bug free. For a while now a lot of us had once stuck to 3.7.2 but hopefully when a lot of us gets better hardware. that wont be the case anymore. Glad that picking a different GZDoom variant helped fix your issue.
