### ISSUE TITLE
DMR using 3-4 bullets for zombiemen, carbine using 5-6 BULLETS when in past versions they  were actually balanced

### ISSUE THREAD

**Issue by duc83** [pa1nki113r/Project_Brutality#913]
dmr buffed, carbine nerfed, carbine literally uses more bullets than the dmr to do the same damage, i don't know if this is a bug or an executive decision in favor of the HDMR overhaul, but pls fix

**Comment by iamcarrotmaster** [comment]
> dmr buffed, carbine nerfed, carbine literally uses more bullets than the dmr to do the same damage, i don't know if this is a bug or an executive decision in favor of the HDMR overhaul, but pls fix

this could be two things, 
there was a bug we fixed where the DMR has the same damage as the HDMR
also we need to rework the functionality of the carbine to be more distinct from the DMR and actually have a place in the arsenal
in either case you should update to the latest version and hold tight till we tweak the carbine

**Comment by duc83** [comment]
oke, thanks

**Comment by duc83** [comment]
for some reason i'm still getting the bug where HMDR and DMR do same damage even when im running with the latest updates (just now tried latest jmartinez build). also is there somewhere with previous versions of the branches? cause like i wanna play them again

**Comment by duc83** [comment]
maybe its because i have older versions of the branches and the bugs from there link with the newer versions or something, i dont know if thats how it works lol

**Comment by JMartinez9820** [comment]
> for some reason i'm still getting the bug where HMDR and DMR do same damage even when im running with the latest updates (just now tried latest jmartinez build). also is there somewhere with previous versions of the branches? cause like i wanna play them again

DMR damage is slightly less compared to the HDMR, DMR is 22 while HDMR is 30.
